# Generated by Django 2.2.7 on 2019-11-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='ЧПУ')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_work', models.TextField(verbose_name='Время работы')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение фильма')),
                ('status', models.BooleanField(default=None, verbose_name='Работа фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.TextField(verbose_name='Количество по горизонтали')),
                ('column', models.TextField(verbose_name='Количество по вертикали')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('type', models.CharField(max_length=100, verbose_name='Тип фильма')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Films')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Halls')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
    ]
