# Generated by Django 2.2.7 on 2019-11-09 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='ЧПУ')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок страницы')),
                ('home_page', models.BooleanField(default=False, verbose_name='Стартовая страница')),
                ('allow_comment', models.BooleanField(default=False, verbose_name='Разрешить ставить комментарий')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 10, 29, 50, 446409), verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Страницa',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок компонента')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название компонента')),
                ('value', models.TextField(blank=True, default=None, null=True, verbose_name='Значения')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Pages')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('value', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 9, 10, 29, 50, 464299), verbose_name='Дата создания')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Pages')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
